name: Test
on:
  workflow_dispatch:

jobs:
  test_env:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 配置 GITHUB_TOKEN 的權限

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv

    - name: Pass Token and Run Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python test.py
