name: 训练和发布AI训练数据

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 您可以根据需要调整 Python 版本

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行 Train.py
        run: |
          python Train.py

      - name: 覆盖模型文件
        run: |
          # 假设模型文件已经生成，这里将其重命名为 "snake_dqn_latest.pth"
          mv path_to_your_model_file.pth snake_dqn_latest.pth

      - name: 运行 post_release_ai_train_data.py
        run: |
          python post_release_ai_train_data.py
