name: Train and Post Process AI Snake
on:
  workflow_dispatch:

jobs:
  train_and_process:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy torch requests

    # Step 4: Run Train.py
    - name: Train model
      run: |
        python Train.py
      env:
        MODEL_PATH: "snake_dqn_latest.pth" # Specify the model file path
        TRAIN_RESULTS_PATH: "./train_results"

    # Step 5: Run post_release_ai_train_data.py
    - name: Post-process training data
      env:
        GITHUB_TOKEN: ${{ secrets.AI_SNAKE_TRAIN_POST_RELEASE }}
      run: |
        python post_release_ai_train_data.py
