name: Train Snake AI

on:
  workflow_dispatch:  # 支援手動觸發

permissions:
  contents: write  # 授予推送權限

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug environment
        run: |
          python --version
          pip list
          ls -al

      - name: Record start time
        run: echo "Training started at: $(date)"

      - name: Run training script
        env:
          AI_SNAKE_SECRET: ${{ secrets.AI_SNAKE_SECRET }}
        run: |
          python Train.py || exit 1
          echo "Training completed."

      - name: Save model to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Save local changes before pull" || echo "No changes to commit"
          git pull origin main --rebase
          git add snake_dqn_latest.pth
          git commit -m "Update: Trained model saved"
          git push origin main

      - name: Upload Training Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python post_release_ai_train_data.py
          echo "Training results uploaded as release."

      - name: Record end time
        run: echo "Training ended at: $(date)"
