name: Train and Push AI Snake Model
on:
  workflow_dispatch:

jobs:
  train_and_push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy torch requests

    # Step 4: Run Train.py
    - name: Train model
      run: |
        python Train.py

    # Step 5: Authenticate and Push model file
    - name: Push model file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git pull origin main
        git add snake_dqn_latest.pth
        git commit -m "Update snake_dqn_latest.pth with latest training results" || echo "No changes to commit"
        git push origin HEAD:main
