name: Train Snake AI

on:
  push:
    branches:
      - main 

jobs: 
  train:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install numpy torch

      - name: Run training script
        env:
          AI_SNAKE_SECRET: ${{ secrets.AI_SNAKE_SECRET }}
        run: |
          python Main.py
          echo "Training completed."

      - name: Save model to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f dqn_snake_model2.pth ]; then
            echo "Model file exists. Proceeding to commit."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add dqn_snake_model2.pth
            git commit -m "Update: Trained model saved"
            git push origin main
          else
            echo "Model file does not exist. Skipping commit."
