name: Train Snake AI

on:
  workflow_dispatch:  # 支援手動觸發

permissions:
  contents: write  # 授予推送權限

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy torch requests

      - name: Run training script
        env:
          AI_SNAKE_SECRET: ${{ secrets.AI_SNAKE_TRAIN }}
        run: |
          python Train.py
          echo "Training completed."

      - name: Save model to repository
        env:
          GITHUB_TOKEN: ${{ secrets.AI_SNAKE_TRAIN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Save local changes before pull" || echo "No changes to commit"
          git pull origin main --rebase || echo "No changes to pull"
          git add snake_dqn_latest.pth || echo "No model file to add"
          git commit -m "Update: Trained model saved" || echo "No changes to commit"
          git push origin main --force || echo "Nothing to push"
      

      - name: Upload Training Results
        env:
          GITHUB_TOKEN: ${{ secrets.AI_SNAKE_TRAIN_POST_RELEASE }}
        run: |
          python post_release_ai_train_data.py
          echo "Training results uploaded as release."
